"""add credentials_version to users

Revision ID: 09f392236159
Revises: e0d33beeede6
Create Date: 2026-09-07 21:44:19.702904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09f392236159'
down_revision: Union[str, None] = 'e0d33beeede6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials_version')
    # ### end Alembic commands ###
