"""add matchday label

Revision ID: 1d0218bddf95
Revises: a181821c9476
Create Date: 2026-09-05 16:49:23.156918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d0218bddf95'
down_revision: Union[str, None] = 'a181821c9476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchdays', sa.Column('label', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchdays', 'label')
    # ### end Alembic commands ###
