"""add competition schedule_url

Revision ID: a181821c9476
Revises: 8568695d8d41
Create Date: 2026-09-05 16:30:05.470111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a181821c9476'
down_revision: Union[str, None] = '8568695d8d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('schedule_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'schedule_url')
    # ### end Alembic commands ###
