"""make coach external_id nullable

Revision ID: f2806bcaae2f
Revises: 1d0218bddf95
Create Date: 2026-09-06 02:45:24.148561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2806bcaae2f'
down_revision: Union[str, None] = '1d0218bddf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaches', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaches', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
