"""add position_verified to players

Revision ID: feaae23bb208
Revises: 09f392236159
Create Date: 2026-09-07 21:52:52.947860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'feaae23bb208'
down_revision: Union[str, None] = '09f392236159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('position_verified', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'position_verified')
    # ### end Alembic commands ###
